# Generated by Django 4.2.3 on 2023-07-09 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("helloAPI", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30)),
                ("address", models.TextField(max_length=100)),
                ("phone", models.CharField(max_length=12)),
                ("about", models.TextField(max_length=100)),
                (
                    "job_applied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="helloAPI.job"
                    ),
                ),
            ],
        ),
    ]
